program: train_lightning.py
command:
  - ${env}
  - python3
  - ${program}
method: bayes
metric:
  name: valid_acc
  goal: maximize
parameters:
  lr:
    distribution: uniform
    min: 1e-7
    max: 1e-3
  model:
    values:
      - 'ResNet18'
      - 'ResNet34'
      - 'ResNet50'
  epochs:
    distribution: categorical
    values:
      - 100
      - 200
      - 300
      - 400
      - 500
      - 600

  batch_size:
    values:
      - 64
      - 128
      - 256
      - 512
#   weight_decay:
#     distribution: uniform
#     min: 1e-7
#     max: 1e-4
#   features_start:
#     distribution: categorical
#     values:
#       - 8
#       - 16
#       - 32
#       - 64
#       - 128
#   grad_batches:
#     distribution: int_uniform
#     min: 1
#     max: 10
  grad_clip:
    min: 0.7
    max: 2.0