program: train_lightning.py
command:
  - ${env}
  - python3
  - ${program}
method: bayes
metric:
  name: val_loss_epoch
  goal: minimize
parameters:
  lr:
    distribution: uniform
    min: 1e-7
    max: 1e-4
  batch_size:
    values:
      - 16
      - 32
#   weight_decay:
#     distribution: uniform
#     min: 1e-7
#     max: 1e-4
#   features_start:
#     distribution: categorical
#     values:
#       - 8
#       - 16
#       - 32
#       - 64
#       - 128
#   grad_batches:
#     distribution: int_uniform
#     min: 1
#     max: 10
  grad_clip:
#     distrubution: log_uniform
    min: 0.5
    max: 1.0