# Training and Test File Locations

test_datapath: /home/oalterkait/PilarData/PilarDataTest512.h5
train_datapath: /home/oalterkait/PilarData/PilarDataTrain512.h5
valid_datapath: /home/oalterkait/PilarData/PilarDataValid512.h5



# Training Parameters

shuffle_mode: seq
## wandb file location
project: lareqnn
## number of gpus to use (format each on new line: - 0, - 1, ...)
gpus:
- 0
- 1



# Hyperparameters

model: ResNet50
lr: 0.00005
epochs: 1024
steps_per_epoch: 256
batch_size: 512
grad_batches: 1
grad_clip: 1
weight_decay: 0.01
label_smoothing: 0.1



# Preprocessing Values

## Take sqrt of data
sqrt: true
normalize: false
norm_mean: 0.65
norm_std: 0.57
clip: true
clip_min: 0.0
clip_max: 1.0
